import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidenav from "./HomeComponents/sideNav";
import Mobilenav from "./HomeComponents/mobilenav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vishwas Portfolio",
  description: "Generated by Vishwas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="fixed bottom-0 w-full lg:hidden">
          <Mobilenav />
        </div>
        <div className="flex justify-center w-full md:pt-20 pt-5">
          <div className="max-w-[1536px] xl:w-[85%]  w-[90%]">
            <div className="xl:flex xl:justify-center gap-x-6 ">
              <Sidenav />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
